---
title: "'<typename>' 형식은 'System.Exception' 또는 'System.Exception'에서 상속한 클래스가 아니므로 'Catch'로 이 형식을 catch할 수 없습니다."
ms.date: 07/20/2015
f1_keywords:
- vbc30392
- bc30392
helpviewer_keywords:
- BC30392
ms.assetid: 1d513d1d-38f5-4b4e-95bb-9f1209553803
ms.openlocfilehash: 9a309896fa66e657319d98d127221cccc6f0488d
ms.sourcegitcommit: bf5c5850654187705bc94cc40ebfb62fe346ab02
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 09/23/2020
ms.locfileid: "91082222"
---
# <a name="catch-cannot-catch-type-typename-because-it-is-not-systemexception-or-a-class-that-inherits-from-systemexception"></a>'\<typename>' 형식은 'System.Exception' 또는 'System.Exception'에서 상속한 클래스가 아니므로 'Catch'로 이 형식을 catch할 수 없습니다.

`Catch` 는 예외를 가로챌 수만 있는데 예외에서 파생되지 않은 요소를 catch하려고 했습니다.  
  
 **오류 ID:** BC30392  
  
## <a name="to-correct-this-error"></a>이 오류를 해결하려면  
  
1. `Catch` 문을 제거하거나 `Catch` 의 대상을 실제 예외로 변경합니다.  
  
## <a name="see-also"></a>참조

- [Try ... Catch ... Finally 문](../language-reference/statements/try-catch-finally-statement.md)
