---
title: 예외 및 예외 처리 - C# 프로그래밍 가이드
description: 예외 및 예외 처리에 대해 알아봅니다. 해당 C# 기능은 프로그램이 실행 중일 때 발생하는 예기치 않은 문제나 예외 상황을 처리하는 데 도움이 됩니다.
ms.date: 07/20/2015
helpviewer_keywords:
- exception handling [C#]
- exceptions [C#]
- C# language, exceptions
ms.assetid: 0001887f-4fa2-47e2-8034-2819477e2344
ms.openlocfilehash: 4be327be4e183d60e440358254aeb9c68fcf25ca
ms.sourcegitcommit: 6f58a5f75ceeb936f8ee5b786e9adb81a9a3bee9
ms.translationtype: HT
ms.contentlocale: ko-KR
ms.lasthandoff: 07/28/2020
ms.locfileid: "87303389"
---
# <a name="exceptions-and-exception-handling-c-programming-guide"></a><span data-ttu-id="2c543-104">예외 및 예외 처리(C# 프로그래밍 가이드)</span><span class="sxs-lookup"><span data-stu-id="2c543-104">Exceptions and Exception Handling (C# Programming Guide)</span></span>

<span data-ttu-id="2c543-105">C# 언어의 예외 처리 기능은 프로그램이 실행 중일 때 발생하는 예기치 않은 문제나 예외 상황을 처리하는 데 도움이 됩니다.</span><span class="sxs-lookup"><span data-stu-id="2c543-105">The C# language's exception handling features help you deal with any unexpected or exceptional situations that occur when a program is running.</span></span> <span data-ttu-id="2c543-106">예외 처리는 `try`, `catch` 및 `finally` 키워드를 사용하여 실패했을 수 있는 작업을 시도하고, 실패를 처리하는 것이 적절하다고 판단될 때 처리하고, 리소스를 정리합니다.</span><span class="sxs-lookup"><span data-stu-id="2c543-106">Exception handling uses the `try`, `catch`, and `finally` keywords to try actions that may not succeed, to handle failures when you decide that it is reasonable to do so, and to clean up resources afterward.</span></span> <span data-ttu-id="2c543-107">예외는 CLR(공용 언어 런타임), .NET, 타사 라이브러리 또는 애플리케이션 코드에서 생성될 수 있습니다.</span><span class="sxs-lookup"><span data-stu-id="2c543-107">Exceptions can be generated by the common language runtime (CLR), by .NET or third-party libraries, or by application code.</span></span> <span data-ttu-id="2c543-108">예외는 `throw` 키워드를 사용하여 생성됩니다.</span><span class="sxs-lookup"><span data-stu-id="2c543-108">Exceptions are created by using the `throw` keyword.</span></span>

<span data-ttu-id="2c543-109">대부분의 경우 코드에서 직접 호출한 메서드가 아니라 호출 스택에서 추가로 작동 중단된 다른 메서드에 의해 예외가 throw될 수 있습니다.</span><span class="sxs-lookup"><span data-stu-id="2c543-109">In many cases, an exception may be thrown not by a method that your code has called directly, but by another method further down in the call stack.</span></span> <span data-ttu-id="2c543-110">이 경우 CLR에서는 스택을 해제하고 특정 예외 형식에 대해 `catch` 블록이 있는 메서드를 찾은 다음 이러한 `catch` 블록을 먼저 실행합니다.</span><span class="sxs-lookup"><span data-stu-id="2c543-110">When this happens, the CLR will unwind the stack, looking for a method with a `catch` block for the specific exception type, and it will execute the first such `catch` block that if finds.</span></span> <span data-ttu-id="2c543-111">호출 스택에서 적절한 `catch` 블록을 찾지 못하면 프로세스를 종료하고 사용자에게 메시지를 표시합니다.</span><span class="sxs-lookup"><span data-stu-id="2c543-111">If it finds no appropriate `catch` block anywhere in the call stack, it will terminate the process and display a message to the user.</span></span>

<span data-ttu-id="2c543-112">이 예제에서 메서드는 0으로 나누기를 테스트하고 오류를 catch합니다.</span><span class="sxs-lookup"><span data-stu-id="2c543-112">In this example, a method tests for division by zero and catches the error.</span></span> <span data-ttu-id="2c543-113">예외 처리를 사용하지 않을 경우 이 프로그램은 **DivideByZeroException이(가) 처리되지 않았습니다.** 오류를 나타내며 종료됩니다.</span><span class="sxs-lookup"><span data-stu-id="2c543-113">Without the exception handling, this program would terminate with a **DivideByZeroException was unhandled** error.</span></span>

[!code-csharp[csProgGuideExceptions#18](~/samples/snippets/csharp/VS_Snippets_VBCSharp/csProgGuideExceptions/CS/Exceptions.cs#18)]

## <a name="exceptions-overview"></a><span data-ttu-id="2c543-114">예외 개요</span><span class="sxs-lookup"><span data-stu-id="2c543-114">Exceptions Overview</span></span>

<span data-ttu-id="2c543-115">예외는 다음과 같은 속성을 갖습니다.</span><span class="sxs-lookup"><span data-stu-id="2c543-115">Exceptions have the following properties:</span></span>

- <span data-ttu-id="2c543-116">모든 예외는 궁극적으로 `System.Exception`에서 파생되는 형식입니다.</span><span class="sxs-lookup"><span data-stu-id="2c543-116">Exceptions are types that all ultimately derive from `System.Exception`.</span></span>
- <span data-ttu-id="2c543-117">예외를 throw할 수 있는 문 주위에 `try` 블록을 사용합니다.</span><span class="sxs-lookup"><span data-stu-id="2c543-117">Use a `try` block around the statements that might throw exceptions.</span></span>
- <span data-ttu-id="2c543-118">`try` 블록에서 예외가 발생하면 제어 흐름이 호출 스택에 있는 첫 번째 관련 예외 처리기로 이동됩니다.</span><span class="sxs-lookup"><span data-stu-id="2c543-118">Once an exception occurs in the `try` block, the flow of control jumps to the first associated exception handler that is present anywhere in the call stack.</span></span> <span data-ttu-id="2c543-119">C#에서 `catch` 키워드는 예외 처리기를 정의하는 데 사용됩니다.</span><span class="sxs-lookup"><span data-stu-id="2c543-119">In C#, the `catch` keyword is used to define an exception handler.</span></span>
- <span data-ttu-id="2c543-120">지정된 예외에 대한 예외 처리기가 없으면 프로그램은 오류 메시지를 나타내며 실행을 중지합니다.</span><span class="sxs-lookup"><span data-stu-id="2c543-120">If no exception handler for a given exception is present, the program stops executing with an error message.</span></span>
- <span data-ttu-id="2c543-121">예외를 처리하고 애플리케이션을 알려진 상태로 둘 수 없으면 예외를 catch하지 마세요.</span><span class="sxs-lookup"><span data-stu-id="2c543-121">Do not catch an exception unless you can handle it and leave the application in a known state.</span></span> <span data-ttu-id="2c543-122">`System.Exception`을 catch하는 경우 `catch` 블록 끝에서 `throw` 키워드를 사용하여 다시 throw하세요.</span><span class="sxs-lookup"><span data-stu-id="2c543-122">If you catch `System.Exception`, re-throw it using the `throw` keyword at the end of the `catch` block.</span></span>
- <span data-ttu-id="2c543-123">`catch` 블록이 예외 변수를 정의하는 경우 이 변수를 사용하여 발생한 예외 형식에 대한 추가 정보를 얻을 수 있습니다.</span><span class="sxs-lookup"><span data-stu-id="2c543-123">If a `catch` block defines an exception variable, you can use it to obtain more information about the type of exception that occurred.</span></span>
- <span data-ttu-id="2c543-124">`throw` 키워드를 사용하여 프로그램에서 명시적으로 예외를 생성할 수 있습니다.</span><span class="sxs-lookup"><span data-stu-id="2c543-124">Exceptions can be explicitly generated by a program by using the `throw` keyword.</span></span>
- <span data-ttu-id="2c543-125">예외 개체는 호출 스택의 상태 및 오류에 대한 텍스트 설명 같은 오류에 대한 자세한 정보를 포함합니다.</span><span class="sxs-lookup"><span data-stu-id="2c543-125">Exception objects contain detailed information about the error, such as the state of the call stack and a text description of the error.</span></span>
- <span data-ttu-id="2c543-126">`finally` 블록의 코드는 예외가 throw되더라도 실행됩니다.</span><span class="sxs-lookup"><span data-stu-id="2c543-126">Code in a `finally` block is executed even if an exception is thrown.</span></span> <span data-ttu-id="2c543-127">`finally` 블록을 사용하여 `try` 블록에서 열려 있는 스트림이나 파일을 닫는 것처럼 리소스를 해제합니다.</span><span class="sxs-lookup"><span data-stu-id="2c543-127">Use a `finally` block to release resources, for example to close any streams or files that were opened in the `try` block.</span></span>
- <span data-ttu-id="2c543-128">.NET의 관리되는 예외는 Win32 구조적 예외 처리 메커니즘을 토대로 구현됩니다.</span><span class="sxs-lookup"><span data-stu-id="2c543-128">Managed exceptions in .NET are implemented on top of the Win32 structured exception handling mechanism.</span></span> <span data-ttu-id="2c543-129">자세한 내용은 [구조적 예외 처리(C/C++)](/cpp/cpp/structured-exception-handling-c-cpp) 및 [Win32 구조적 예외 처리에 대한 집중 과정](http://bytepointer.com/resources/pietrek_crash_course_depths_of_win32_seh.htm)을 참조하세요.</span><span class="sxs-lookup"><span data-stu-id="2c543-129">For more information, see [Structured Exception Handling (C/C++)](/cpp/cpp/structured-exception-handling-c-cpp) and [A Crash Course on the Depths of Win32 Structured Exception Handling](http://bytepointer.com/resources/pietrek_crash_course_depths_of_win32_seh.htm).</span></span>

## <a name="related-sections"></a><span data-ttu-id="2c543-130">관련 단원</span><span class="sxs-lookup"><span data-stu-id="2c543-130">Related Sections</span></span>

<span data-ttu-id="2c543-131">예외 및 예외 처리에 대한 자세한 내용은 다음 아티클을 참조하세요.</span><span class="sxs-lookup"><span data-stu-id="2c543-131">See the following articles for more information about exceptions and exception handling:</span></span>

- [<span data-ttu-id="2c543-132">예외 사용</span><span class="sxs-lookup"><span data-stu-id="2c543-132">Using Exceptions</span></span>](using-exceptions.md)
- [<span data-ttu-id="2c543-133">예외 처리</span><span class="sxs-lookup"><span data-stu-id="2c543-133">Exception Handling</span></span>](exception-handling.md)
- [<span data-ttu-id="2c543-134">예외 만들기 및 Throw</span><span class="sxs-lookup"><span data-stu-id="2c543-134">Creating and Throwing Exceptions</span></span>](creating-and-throwing-exceptions.md)
- [<span data-ttu-id="2c543-135">컴파일러 생성 예외</span><span class="sxs-lookup"><span data-stu-id="2c543-135">Compiler-Generated Exceptions</span></span>](compiler-generated-exceptions.md)
- [<span data-ttu-id="2c543-136">try/catch를 사용하여 예외를 처리하는 방법(C# 프로그래밍 가이드)</span><span class="sxs-lookup"><span data-stu-id="2c543-136">How to handle an exception using try/catch (C# Programming Guide)</span></span>](how-to-handle-an-exception-using-try-catch.md)
- [<span data-ttu-id="2c543-137">finally를 사용하여 정리 코드를 실행하는 방법</span><span class="sxs-lookup"><span data-stu-id="2c543-137">How to execute cleanup code using finally</span></span>](how-to-execute-cleanup-code-using-finally.md)
- [<span data-ttu-id="2c543-138">CLS 규격이 아닌 예외를 catch하는 방법</span><span class="sxs-lookup"><span data-stu-id="2c543-138">How to catch a non-CLS exception</span></span>](how-to-catch-a-non-cls-exception.md)

## <a name="c-language-specification"></a><span data-ttu-id="2c543-139">C# 언어 사양</span><span class="sxs-lookup"><span data-stu-id="2c543-139">C# Language Specification</span></span>

<span data-ttu-id="2c543-140">자세한 내용은 [C# 언어 사양](/dotnet/csharp/language-reference/language-specification/introduction)의 [예외](~/_csharplang/spec/exceptions.md)를 참조하세요.</span><span class="sxs-lookup"><span data-stu-id="2c543-140">For more information, see [Exceptions](~/_csharplang/spec/exceptions.md) in the [C# Language Specification](/dotnet/csharp/language-reference/language-specification/introduction).</span></span> <span data-ttu-id="2c543-141">언어 사양은 C# 구문 및 사용법에 대 한 신뢰할 수 있는 소스 됩니다.</span><span class="sxs-lookup"><span data-stu-id="2c543-141">The language specification is the definitive source for C# syntax and usage.</span></span>

## <a name="see-also"></a><span data-ttu-id="2c543-142">참고 항목</span><span class="sxs-lookup"><span data-stu-id="2c543-142">See also</span></span>

- <xref:System.SystemException>
- [<span data-ttu-id="2c543-143">C# 프로그래밍 가이드</span><span class="sxs-lookup"><span data-stu-id="2c543-143">C# Programming Guide</span></span>](../index.md)
- [<span data-ttu-id="2c543-144">C# 키워드</span><span class="sxs-lookup"><span data-stu-id="2c543-144">C# Keywords</span></span>](../../language-reference/keywords/index.md)
- [<span data-ttu-id="2c543-145">throw</span><span class="sxs-lookup"><span data-stu-id="2c543-145">throw</span></span>](../../language-reference/keywords/throw.md)
- [<span data-ttu-id="2c543-146">try-catch</span><span class="sxs-lookup"><span data-stu-id="2c543-146">try-catch</span></span>](../../language-reference/keywords/try-catch.md)
- [<span data-ttu-id="2c543-147">try-finally</span><span class="sxs-lookup"><span data-stu-id="2c543-147">try-finally</span></span>](../../language-reference/keywords/try-finally.md)
- [<span data-ttu-id="2c543-148">try-catch-finally</span><span class="sxs-lookup"><span data-stu-id="2c543-148">try-catch-finally</span></span>](../../language-reference/keywords/try-catch-finally.md)
- [<span data-ttu-id="2c543-149">예외</span><span class="sxs-lookup"><span data-stu-id="2c543-149">Exceptions</span></span>](../../../standard/exceptions/index.md)
